WhatsappIntegration/Controllers/InboxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WhatsappIntegration.DAL.Abstract;
using WhatsappIntegration.DAL.Concrete.EFCore;
using WhatsappIntegration.DAL.Context;
using WhatsappIntegration.Entity.Concrete;
using WhatsappIntegration.Utility;

namespace WhatsappIntegration.WebUI.Controllers
{
    [Authorize]
    public class InboxController : Controller
    {
        IdentityContext context;
        private IUnitOfWork unitOfWork;
        private UserManager<UserAgent> userManager;
        public InboxController(IUnitOfWork _unitOfWork, IdentityContext _context, UserManager<UserAgent> _userManager)
        {
            unitOfWork = _unitOfWork;
            context = _context;
            userManager = _userManager;
        }
        public async Task<IActionResult> Index(int? pageNumber)
        {
            var user = await userManager.GetUserAsync(User);
            var result = unitOfWork.VChatList.Find(f=>f.CompanyId ==user.CompanyId);
            if (result != null)
            {
                //foreach (var item in result)
                //{
                //    item.UnreadMessageCount = unitOfWork.ChatMessages.GetUnreadMessageCount(item.ChatId);
                //}
                int pageSize = 2;
                return View(PaginatedList<VChatList>.Create(result.AsNoTracking(), pageNumber ?? 1, pageSize));
            }
            return View();
        }

        [HttpPost]
        public PartialViewResult ChatBox(int chatId, string person, string phone)
        {
            int take = 8;
            ViewBag.Person = person; ViewBag.Phone = phone; ViewBag.ChatId = chatId; ViewBag.Take = take;
            var chatMessages = unitOfWork.ChatMessages.GetAll()
                .Where(f => f.ChatId == chatId)
                .OrderByDescending(o => o.ChatMessageId)
                .Take(take)
                .ToList();
            unitOfWork.ChatMessages.SetUnreadToRead(chatId);
            return PartialView(chatMessages);
        }

        [HttpPost]
        public JsonResult SkipTakeMessages(int chatId, int skip, int take)
        {
            var chatMessages = unitOfWork.ChatMessages.GetAll()
                .Where(f => f.ChatId == chatId)
                .OrderByDescending(o => o.ChatMessageId)
                .Skip(skip)
                .Take(take)
                .ToList();

            return Json(chatMessages);
        }

        [HttpPost]
        public JsonResult ChangeSmartReplyState(int chatId, bool state)
        {
            var chat = unitOfWork.Chat.Find(f => f.ChatId == chatId && f.SmartReplyState != state).FirstOrDefault();
            if (chat != null)
            {
                chat.SmartReplyState = state;
                unitOfWork.Chat.Update(chat);
                unitOfWork.SaveChanges();
                return Json(new { state = "success" });
            }
            return Json(NotFound());
        }
    }
}

WhatsappIntegration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Whatsapp Integration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/_layout.css" rel="stylesheet" />
</head>
<body class="body">
    <div class="wrapper">
        <div id="sidebar">
            @await Html.PartialAsync("~/Views/Shared/_SideBar.cshtml")
        </div>
        <div id="content" class="container-fluid">
            <div id="topbar">
                @await Html.PartialAsync("~/Views/Shared/_TopBar.cshtml")

            </div>
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/microsoft-signalr/signalr.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WhatsappIntegration/Views/Shared/_SideBar.cshtml
<div id="side-bar-container">
    <div class="text-center">
        <div id="sidebar-orange">
        </div>
        <div id="gunesbros">
            <svg viewBox="0 0 100 100">
                <circle cx="50" cy="50" r="30" stroke="black" stroke-width="3" fill="black" />
                <text x="50%" y="50%" text-anchor="middle" font-size="16px" stroke="white" stroke-width="1.5px" dy=".3em">gunesbro's</text>
                Sorry, your browser does not support inline SVG.
            </svg>
        </div>

    </div>
    <div class="links-container">
        <div class="links">
            <a asp-action="Index" asp-controller="Home" class="a-link">
                <div class="float-left">
                    <svg class="svg-icon" viewBox="0 0 25 25">
                        <path fill="none" d="M19.629,9.655c-0.021-0.589-0.088-1.165-0.21-1.723h-3.907V7.244h1.378V6.555h-2.756V5.866h2.067V5.177h-0.689V4.488h-1.378V3.799h0.689V3.11h-1.378V2.421h0.689V1.731V1.294C12.88,0.697,11.482,0.353,10,0.353c-5.212,0-9.446,4.135-9.629,9.302H19.629z M6.555,2.421c1.522,0,2.756,1.234,2.756,2.756S8.077,7.933,6.555,7.933S3.799,6.699,3.799,5.177S5.033,2.421,6.555,2.421z"></path>
                        <path fill="none" d="M12.067,18.958h-0.689v-0.689h2.067v-0.689h0.689V16.89h2.067v-0.689h0.689v-0.689h-1.378v-0.689h-2.067v-0.689h1.378v-0.689h2.756v-0.689h-1.378v-0.689h3.218c0.122-0.557,0.189-1.134,0.21-1.723H0.371c0.183,5.167,4.418,9.302,9.629,9.302c0.711,0,1.401-0.082,2.067-0.227V18.958z"></path>
                    </svg>
                </div>
                <div class="sidebar-links-container">
                    <header class="sidebar-links">Dashboard</header>
                </div>
            </a>
        </div>
        <div class="links">
            <a asp-action="Index" asp-controller="Inbox" class="a-link">
                <div class="float-left">
                    <svg class="svg-icon" viewBox="0 0 25 25">
                        <polygon fill="none" points="18.198,7.95 3.168,7.95 3.168,8.634 9.317,9.727 9.317,19.564 12.05,19.564 12.05,9.727 18.198,8.634 "></polygon>
                        <path fill="none" d="M2.485,10.057v-3.41H2.473l0.012-4.845h1.366c0.378,0,0.683-0.306,0.683-0.683c0-0.378-0.306-0.683-0.683-0.683H1.119c-0.378,0-0.683,0.306-0.683,0.683c0,0.378,0.306,0.683,0.683,0.683h0.683v4.845C1.406,6.788,1.119,7.163,1.119,7.609v2.733c0,0.566,0.459,1.025,1.025,1.025c0.053,0,0.105-0.008,0.157-0.016l-0.499,5.481l5.9,2.733h0.931C8.634,13.266,5.234,10.458,2.485,10.057z"></path>
                        <path fill="none" d="M18.169,6.584c-0.303-3.896-3.202-6.149-7.486-6.149c-4.282,0-7.183,2.252-7.484,6.149H18.169z M15.463,3.187c0.024,0.351-0.103,0.709-0.394,0.977c-0.535,0.495-1.405,0.495-1.94,0c-0.29-0.268-0.418-0.626-0.394-0.977C13.513,3.827,14.683,3.827,15.463,3.187z"></path>
                        <path fill="none" d="M18.887,10.056c-2.749,0.398-6.154,3.206-6.154,9.508h0.933l5.899-2.733L18.887,10.056z"></path>
                    </svg>
                </div>
                <div>
                    <header class="sidebar-links">Inbox</header>
                </div>
            </a>
        </div>
        <div class="links">
            <a href="#" class="a-link">
                <div class="float-left">
                    <svg class="svg-icon" viewBox="0 0 25 25">
                        <path fill="none" d="M7.83,3.404l1.741-2.909C9.367,0.407,9.15,0.344,8.913,0.344c-0.954,0-1.728,0.774-1.728,1.728C7.185,2.613,7.441,3.087,7.83,3.404z"></path>
                        <path fill="none" d="M19.645,12.002l-0.464-0.31c-0.09-1.505-0.628-2.972-1.575-4.187l-1.212,0.156l0.084-0.125c0.316-0.473,0.188-1.119-0.286-1.435L15.517,5.65c-0.473-0.316-1.119-0.187-1.435,0.286l-0.095,0.142l-0.538-3.219l-3.271-2.033l-1.754,2.93l0.86,0.481L3.04,3.445L2.136,4.798l3.766,2.516c-0.17,0.204-0.333,0.414-0.484,0.639C5.269,8.178,5.137,8.41,5.013,8.645L1.247,6.129L0.344,7.482l4.878,8.537l0.008-0.013c0.098,0.164,0.207,0.322,0.317,0.479l1.628-0.209l-0.302,0.452c-0.316,0.473-0.187,1.119,0.286,1.435l0.675,0.451c0.473,0.316,1.119,0.188,1.435-0.286l0.252-0.378l0.185,1.442c1.418,0.385,2.904,0.334,4.273-0.105l0.552,0.369c1.512-0.533,2.87-1.542,3.829-2.977C19.32,15.244,19.732,13.602,19.645,12.002z M14.09,16.055c-0.106,0.158-0.32,0.201-0.478,0.095c-0.158-0.106-0.201-0.32-0.095-0.478c0.106-0.158,0.32-0.201,0.478-0.095C14.153,15.682,14.196,15.896,14.09,16.055zM13.969,13.664c-0.513,0.769-1.371,1.227-2.296,1.227c-0.546,0-1.075-0.161-1.531-0.465c-1.265-0.845-1.606-2.561-0.762-3.826c0.513-0.768,1.372-1.227,2.297-1.227c0.545,0,1.074,0.161,1.53,0.465C14.472,10.683,14.814,12.4,13.969,13.664z M15.065,17.476c-0.106,0.158-0.32,0.201-0.478,0.095c-0.158-0.106-0.201-0.32-0.095-0.478c0.106-0.158,0.32-0.201,0.478-0.095C15.129,17.104,15.171,17.318,15.065,17.476z M15.334,14.768c-0.106,0.158-0.32,0.201-0.478,0.095c-0.158-0.106-0.201-0.32-0.095-0.478c0.106-0.158,0.32-0.201,0.478-0.095C15.397,14.396,15.44,14.61,15.334,14.768zM15.568,13.222c-0.158-0.106-0.201-0.32-0.095-0.478c0.106-0.158,0.32-0.201,0.478-0.095c0.158,0.106,0.201,0.32,0.095,0.478C15.94,13.285,15.726,13.327,15.568,13.222z M16.665,15.658c-0.106,0.158-0.32,0.201-0.478,0.095c-0.158-0.106-0.201-0.32-0.095-0.478c0.106-0.158,0.32-0.201,0.478-0.095S16.771,15.499,16.665,15.658z M17.733,13.483c-0.106,0.158-0.32,0.201-0.478,0.095c-0.158-0.106-0.201-0.32-0.095-0.478c0.106-0.158,0.32-0.201,0.478-0.095C17.796,13.111,17.839,13.325,17.733,13.483z"></path>
                        <path fill="none" d="M12.824,10.412c-0.341-0.228-0.738-0.349-1.146-0.349c-0.694,0-1.338,0.344-1.723,0.92c-0.634,0.949-0.377,2.236,0.571,2.869c0.342,0.228,0.739,0.35,1.147,0.35c0.694,0,1.337-0.344,1.722-0.92C14.029,12.332,13.773,11.045,12.824,10.412z"></path>
                    </svg>
                </div>
                <div>
                    <header class="sidebar-links">Settings</header>
                </div>
            </a>
        </div>
    </div>
    <div class="user-box" style="color:white;font-size:14px; margin-top:100%;">
        <div>
            <p style="padding-left:5px;">gunesbro</p>
        </div>
        <div class="bg-dark " style="padding:10px; ">
            <a asp-action="Logout" asp-controller="Account">logout</a>
        </div>
    </div>
</div>

WhatsappIntegration/Views/Shared/_TopBar.cshtml
<div class="topbar-container">
    @*<div class="container-fluid">
        <div class="col-sm-9 padding-0">
            <div class="input-group" style="padding:6px;">
                <input id="search-text" type="text" onkeyup="search()" class="input form-control" placeholder="Type something..." style="background-color:transparent">
                <div class="input-group-append">
                    <input type="submit" class="input-group-text input" id="basic-addon2" value="Search!" style="background-color:#a32d2d;color:white;" />
                </div>
            </div>
        </div>
        <div class="col-sm-3">

        </div>
    </div>
    <div id="search-result-cantainer" class="bg-danger container-fluid">
        <div class="text-center" style="padding:8px;">
            <header><b>No Result!</b></header>
        </div>
    </div>*@
</div>
<script>
    function search() {
        let searchKey = $('#search-text').val();
        let resultContainer = $('#search-result-cantainer');
        if (searchKey != '') {
            resultContainer.css("display", "block");
            resultContainer.addClass("search-result-cantainer-open");

        }
        else {
            resultContainer.removeClass("search-result-cantainer-open");
            resultContainer.css("display", "none");
        }
    }
</script>